default_platform(:ios)

platform :ios do
  desc "Run Smoke Tests"
  lane :smoke_test do
    run_tests(
       workspace: "Hackers.xcworkspace",
       device: "iPhone 8",
       testplan: "Smoke"
    )
  end

  desc "Run Perfomance Tests"
  lane :perfomance_test do
    run_tests(
       workspace: "Hackers.xcworkspace",
       device: "iPhone 8",
       testplan: "Perfomance"
    )
  end
end
